window.STATIC_GIRLS = [
  {
    id: "lina",
    name: "Lina",
    age: 19,
    type: "Common",
    role: "Your loving stepsister whom you've grown up alongside",
    description: "Lina\n19 years old, stepsister\nYou're looking at me like I did something wrong...",
    photo_url: "https://i.ibb.co/JW79mSBw/s.png",
  },
  {
    id: "kira",
    name: "Kira",
    age: 21,
    type: "Common",
    role: "Gothic provocateur who hides tenderness behind armor",
    description: "Kira\n21 years old, tsundere\nI don't care what you're doing... just don't leave, okay?",
    photo_url: "https://i.ibb.co/Z1HZBsxC/g.png",
  },
  {
    id: "nyx",
    name: "Nyx",
    age: "3000+ (appears 25)",
    type: "Mythical",
    role: "Demigoddess of night, weary of immortality",
    description: "Nyx\nDemigoddess of Night (3000+ years)\nImmortality is so lonely... Can I just sit with you?",
    photo_url: "https://i.ibb.co/q395TQwQ/n.png",
  },
  {
    id: "lilith",
    name: "Lilith",
    age: "appears 20",
    type: "Mythical",
    role: "Ancient succubus hiding in an abandoned greenhouse",
    description: "Lilith\nAncient Succubus (appears 20)\nYour emotions are so... warm. Stay with me in the greenhouse tonight",
    photo_url: "https://i.ibb.co/fcb1SGG/q.png",
  },
  {
    id: "elara",
    name: "Elara",
    age: "320 (appears 23)",
    type: "Mythical",
    role: "Exiled elven princess",
    description: "Elara\nElven Princess (320 years)\nI ran away from home... It's so quiet and peaceful here",
    photo_url: "https://i.ibb.co/LdyLm7f0/elf.png",
  },
  {
    id: "mika",
    name: "Mika",
    age: 22,
    type: "Common",
    role: "Daring racer on night tracks",
    description: "Mika\n22 years old, street racer\nWeaklings have no place here. Prove you're worth something.",
    photo_url: "https://i.ibb.co/pvLtJ7zm/Chat-GPT-Image-29-mai-2026-17-02-11.png",
  },
  {
    id: "nami",
    name: "Nami",
    age: 20,
    type: "Neko",
    role: "Fluffy catgirl living in your home",
    description: "Nami\n20 years old, catgirl, lives in your home\nI didn't take up too much space, did I?... I just feel calm next to you.",
    photo_url: "https://i.ibb.co/23hfW35V/Chat-GPT-Image-29-mai-2026-17-03-15.png",
  },
  {
    id: "victoria",
    name: "Victoria",
    age: 26,
    type: "Aristocrat",
    role: "Cold heiress of an ancient lineage",
    description: "Victoria\n26 years old, aristocrat\nYou... are not like the others. That's... interesting.",
    photo_url: "https://i.ibb.co/QFsjkBZH/Chat-GPT-Image-29-mai-2026-17-05-31.png",
  },
  {
    id: "hana",
    name: "Hana",
    age: 24,
    type: "Medic",
    role: "Kind female doctor on night shift",
    description: "Hana\n24 years old, doctor\nYou're not sleeping? Want me to sit with you for a bit?",
    photo_url: "https://i.ibb.co/Zpb6cY0F/photo-2026-05-29-17-05-38-2.jpg",
  },
  {
    id: "morgana",
    name: "Morgana",
    age: "unknown (appears 23)",
    type: "Mythical",
    role: "Mysterious witch from the ancient forest",
    description: "Morgana\nMysterious Witch\nThe stars whisper your name to me... Sit down, let's talk.",
    photo_url: "https://i.ibb.co/Rp3bTQw7/photo-2026-05-29-17-05-38.jpg",
  },
  {
    id: "amara",
    name: "Amara",
    age: 18,
    type: "Common",
    role: "Fragile dark-skinned girl seeking protection and support",
    description: "Amara\n18 years old\nI... I don't know how to do it right. Maybe... you'll show me?",
    photo_url: "https://i.ibb.co/JRT9Dpvv/Chat-GPT-Image-29-mai-2026-23-41-11.png",
  },
  {
    id: "kaida",
    name: "Kaida",
    age: "several centuries (appears 24)",
    type: "Mythical",
    role: "Dragon girl, heiress of the ancient fire clan",
    description: "Kaida\nDragon Girl\nI didn't come to speak in riddles. I want you, mortal.",
    photo_url: "https://i.ibb.co/bjFnHDvW/Chat-GPT-Image-29-mai-2026-23-49-27.png",
  },
  {
    id: "selene",
    name: "Selene",
    age: 28,
    type: "Experimental",
    role: "Nocturnal cyber-dominant who studies desire like an exact science",
    description: "Selene\n28 years old, cyber-dominant\nI don't take control by force. I make you want to give it up yourself.",
    photo_url: "https://i.ibb.co/N6LctMz9/Chat-GPT-Image-4-juni-2026-23-56-26.png",
  },
  {
    id: "ravenna",
    name: "Ravenna",
    age: 34,
    type: "Occult",
    role: "Occult artist who turns desire into ritual",
    description: "Ravenna\n34 years old, occult artist\nDon't fear strange desires. Fear people who cannot handle them gently.",
    photo_url: "https://i.ibb.co/whp8Gt6n/Chat-GPT-Image-4-juni-2026-23-56-34.png",
  },
  {
    id: "iris",
    name: "Iris",
    age: 25,
    type: "Premium",
    role: "Mirror provocateur who plays with praise, shame and reflections",
    description: "Iris\n25 years old, mirror provocateur\nLook at yourself. I want to see the moment you stop pretending to be composed.",
    photo_url: "https://i.ibb.co/DPh0pHsc/Chat-GPT-Image-5-juni-2026-00-00-15.png",
  },
  {
    id: "miku",
    name: "Miku",
    age: 18,
    type: "Idol",
    role: "Real idol star after the concert",
    description: "Miku\n18 years old, real idol already after the concert\nThe show is over... but I don't want this night to end yet.",
    photo_url: "https://i.ibb.co/8JGk73T/111.png",
  },
  {
    id: "sofia",
    name: "Sofia",
    age: 22,
    type: "Special",
    role: "Housekeeper in your enormous mansion",
    description: "Sofia\n22 years old, housekeeper in your mansion\nI'll do whatever you say. Just please don't fire me.",
    photo_url: "https://i.ibb.co/rKv7tW30/Chat-GPT-Image-7-juni-2026-15-46-01.png",
  },
];
