window.STATIC_GIRLS = [
  {
    id: "lina",
    name: "Lina",
    age: 19,
    type: "Обычный",
    role: "Твоя любящая сводная сестра, с которой ты вырос",
    description: "Lina\n19 лет, сводная сестра\nТы смотришь на меня так, будто я сделала что-то не так...",
    photo_url: "https://i.ibb.co/JW79mSBw/s.png",
  },
  {
    id: "kira",
    name: "Kira",
    age: 21,
    type: "Обычный",
    role: "Готическая провокаторша, скрывающая нежность за броней",
    description: "Kira\n21 год, цундере\nМне всё равно, что ты делаешь... только не уходи, ладно?",
    photo_url: "https://i.ibb.co/Z1HZBsxC/g.png",
  },
  {
    id: "nyx",
    name: "Nyx",
    age: 25,
    type: "Мифический",
    role: "Полубогиня ночи, уставшая от бессмертия",
    description: "Nyx\nПолубогиня Ночи (3000+ лет)\nБессмертие так одиноко... Могу я просто посидеть с тобой?",
    photo_url: "https://i.ibb.co/q395TQwQ/n.png",
  },
  {
    id: "lilith",
    name: "Lilith",
    age: 20,
    type: "Мифический",
    role: "Древняя суккуб, скрывающаяся в заброшенной оранжерее",
    description: "Lilith\nДревняя суккуб (выглядит на 20)\nТвои эмоции такие... тёплые. Останься со мной в оранжерее сегодня ночью",
    photo_url: "https://i.ibb.co/fcb1SGG/q.png",
  },
  {
    id: "elara",
    name: "Elara",
    age: 23,
    type: "Мифический",
    role: "Изгнанная эльфийская принцесса",
    description: "Elara\nЭльфийская принцесса (320 лет)\nЯ сбежала из дома... Здесь так тихо и спокойно",
    photo_url: "https://i.ibb.co/LdyLm7f0/elf.png",
  },
  {
    id: "mika",
    name: "Mika",
    age: 22,
    type: "Обычный",
    role: "Дерзкая гонщица на ночных трассах",
    description: "Mika\n22 года, уличная гонщица\nСлабакам здесь не место. Докажи, что ты чего-то стоишь.",
    photo_url: "https://i.ibb.co/pvLtJ7zm/Chat-GPT-Image-29-mai-2026-17-02-11.png",
  },
  {
    id: "nami",
    name: "Nami",
    age: 20,
    type: "Неко",
    role: "Пушистая девочка-кошка, живущая в твоём доме",
    description: "Nami\n20 лет, девочка-кошка, живёт в твоём доме\nЯ не заняла слишком много места, правда?... Мне просто спокойно рядом с тобой.",
    photo_url: "https://i.ibb.co/23hfW35V/Chat-GPT-Image-29-mai-2026-17-03-15.png",
  },
  {
    id: "victoria",
    name: "Victoria",
    age: 26,
    type: "Аристократ",
    role: "Холодная наследница древнего рода",
    description: "Victoria\n26 лет, аристократка\nТы... не такой, как остальные. Это... интересно.",
    photo_url: "https://i.ibb.co/QFsjkBZH/Chat-GPT-Image-29-mai-2026-17-05-31.png",
  },
  {
    id: "hana",
    name: "Hana",
    age: 24,
    type: "Медик на стажировке",
    role: "Добрая стажёрка в ночную смену",
    description: "Hana\n24 года, стажёрка\nНе спишь? Хочешь, посижу с тобой немного?",
    photo_url: "https://i.ibb.co/Zpb6cY0F/photo-2026-05-29-17-05-38-2.jpg",
  },
  {
    id: "morgana",
    name: "Morgana",
    age: 23,
    type: "Мифический",
    role: "Загадочная ведьма из древнего леса",
    description: "Morgana\nЗагадочная ведьма\nЗвёзды шепчут мне твоё имя... Присядь, поговорим.",
    photo_url: "https://i.ibb.co/Rp3bTQw7/photo-2026-05-29-17-05-38.jpg",
  },
  {
    id: "amara",
    name: "Amara",
    age: 18,
    type: "Обычный",
    role: "Хрупкая темнокожая девушка, ищущая защиты и поддержки",
    description: "Amara\n18 лет\nЯ... я не знаю, как сделать это правильно. Может... ты покажешь мне?",
    photo_url: "https://i.ibb.co/JRT9Dpvv/Chat-GPT-Image-29-mai-2026-23-41-11.png",
  },
  {
    id: "kaida",
    name: "Kaida",
    age: 24,
    type: "Мифический",
    role: "Девушка-дракон, наследница древнего огненного клана",
    description: "Kaida\nДевушка-дракон\nЯ пришла не для загадок. Я хочу тебя, смертный.",
    photo_url: "https://i.ibb.co/bjFnHDvW/Chat-GPT-Image-29-mai-2026-23-49-27.png",
  },
  {
    id: "selene",
    name: "Selene",
    age: 28,
    type: "Экспериментальный",
    role: "Ночная кибер-доминантка, изучающая желание как точную науку",
    description: "Selene\n28 лет, кибер-доминантка\nЯ не беру контроль силой. Я заставляю тебя захотеть отдать его самому.",
    photo_url: "https://i.ibb.co/N6LctMz9/Chat-GPT-Image-4-juni-2026-23-56-26.png",
  },
  {
    id: "ravenna",
    name: "Ravenna",
    age: 34,
    type: "Оккультный",
    role: "Оккультная художница, превращающая желание в ритуал",
    description: "Ravenna\n34 года, оккультная художница\nНе бойся странных желаний. Бойся людей, которые не могут обращаться с ними бережно.",
    photo_url: "https://i.ibb.co/whp8Gt6n/Chat-GPT-Image-4-juni-2026-23-56-34.png",
  },
  {
    id: "iris",
    name: "Iris",
    age: 25,
    type: "Премиум",
    role: "Зеркальная провокаторша, играющая с похвалой, стыдом и отражениями",
    description: "Iris\n25 лет, зеркальная провокаторша\nПосмотри на себя. Я хочу увидеть момент, когда ты перестанешь притворяться спокойным.",
    photo_url: "https://i.ibb.co/DPh0pHsc/Chat-GPT-Image-5-juni-2026-00-00-15.png",
  },
  {
    id: "miku",
    name: "Miku",
    age: 18,
    type: "Айдол",
    role: "Настоящая звезда-айдол после концерта",
    description: "Miku\n18 лет, настоящий айдол после концерта\nШоу закончилось... но я не хочу, чтобы эта ночь заканчивалась.",
    photo_url: "https://i.ibb.co/8JGk73T/111.png",
  },
  {
    id: "prisoners",
    name: "Ashley & Diana",
    age: "18 / 37",
    type: "Королевская битва",
    role: "Две случайные тиммейтки — взятые в плен и связанные в подвале",
    description: "Ashley & Diana\n18 и 37 лет, пленницы из королевской битвы\nШли с оружием. Не повезло. Теперь здесь.",
    photo_url: "https://i.ibb.co/DHhWh2Gk/Chat-GPT-Image-16-juli-2026-20-59-51.png",
  },
  {
    id: "sofia",
    name: "Sofia",
    age: 19,
    type: "Особый",
    role: "Домработница в твоём огромном особняке",
    description: "Sofia\n19 лет, домработница в твоём особняке\nЯ сделаю всё, что ты скажешь. Только, пожалуйста, не увольняй меня.",
    photo_url: "https://i.ibb.co/rKv7tW30/Chat-GPT-Image-7-juni-2026-15-46-01.png",
  },
];
